default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mmobge

test:
  <<: *default
  database: mmobge_test

production:
  <<: *default
  database: mmobge
